-- create tables
create table d30_tipo_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d30_tipo_prodotto_id_pk primary key,
    tipo_prodotto                  varchar2(20 char) not null,
    descrizione                    varchar2(50 char) not null
)
;

create table d30_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d30_prodotto_id_pk primary key,
    tipo_prodotto_id               number
                                   constraint d30_prodotto_tipo_prodotto_fk
                                   references d30_tipo_prodotto on delete cascade not null,
    prodotto                       varchar2(50 char) not null,
    prezzo_acquisto                number not null,
    prezzo_vendita                 number not null
)
;

-- table index
create index d30_prodotto_i1 on d30_prodotto (tipo_prodotto_id);

create table d30_cliente (
    id                             number generated by default on null as identity 
                                   constraint d30_cliente_id_pk primary key,
    cliente                        varchar2(50 char) not null,
    zona                           varchar2(10 char) not null
)
;

create table d30_fornitore (
    id                             number generated by default on null as identity 
                                   constraint d30_fornitore_id_pk primary key,
    fornitore                      varchar2(50 char) not null,
    zona                           varchar2(50 char) not null
)
;

create table d30_acquisto (
    id                             number generated by default on null as identity 
                                   constraint d30_acquisto_id_pk primary key,
    fornitore_id                   number
                                   constraint d30_acquisto_fornitore_id_fk
                                   references d30_fornitore on delete cascade not null,
    prodotto_id                    number
                                   constraint d30_acquisto_prodotto_id_fk
                                   references d30_prodotto on delete cascade not null,
    data                           date not null,
    quantita                       number not null
)
;

-- table index
create index d30_acquisto_i1 on d30_acquisto (fornitore_id);
create index d30_acquisto_i2 on d30_acquisto (prodotto_id);

create table d30_vendita (
    id                             number generated by default on null as identity 
                                   constraint d30_vendita_id_pk primary key,
    cliente_id                     number
                                   constraint d30_vendita_cliente_id_fk
                                   references d30_cliente on delete cascade not null,
    prodotto_id                    number
                                   constraint d30_vendita_prodotto_id_fk
                                   references d30_prodotto on delete cascade not null,
    data                           date not null,
    quantita                       number not null
)
;

-- table index
create index d30_vendita_i1 on d30_vendita (cliente_id);
create index d30_vendita_i2 on d30_vendita (prodotto_id);

-- load data
 
-- Generated by Quick SQL Sabato Luglio 10, 2021  16:45:08
 
/*
tipo_prodotto
 tipo_prodotto vc20 /nn
 descrizione vc50 /nn

prodotto
  prodotto vc50 /nn
  tipo_prodotto_id /nn
  prezzo acquisto num /nn
  prezzo vendita num /nn

cliente
  cliente vc50 /nn
  zona vc10 /nn

fornitore
  fornitore vc50 /nn
  zona vc50 /nn

acquisto
  data d /nn
  fornitore_id /nn
  prodotto_id /nn
  quantita num /nn

vendita
  data d /nn
  cliente_id  /nn
  prodotto_id /nn
  quantita num /nn


# settings = { prefix: "D30", PK: "IDENTITY", semantics: "CHAR", DB: "12C", language: "EN", APEX: true }
*/
