-- drop objects
drop table d50_persona cascade constraints;
drop table d50_tipo_appuntamento cascade constraints;
drop table d50_appuntamento cascade constraints;

-- create tables
create table d50_persona (
    id                             number generated by default on null as identity 
                                   constraint d50_persona_id_pk primary key,
    nome                           varchar2(50 char)
                                   constraint d50_persona_nome_unq unique not null,
    email                          varchar2(60 char) not null
)
;

create table d50_tipo_appuntamento (
    id                             number generated by default on null as identity 
                                   constraint d50_tipo_appuntame_id_pk primary key,
    codice                         varchar2(50 char)
                                   constraint d50_tipo_appuntame_codice_unq unique not null,
    descrizione                    varchar2(100 char) not null,
    classe_colore                  varchar2(50 char)
)
;

create table d50_appuntamento (
    id                             number generated by default on null as identity 
                                   constraint d50_appuntamento_id_pk primary key,
    tipo_appuntamento_id           number
                                   constraint d50_appuntame_tipo_appuntam_fk
                                   references d50_tipo_appuntamento on delete cascade not null,
    persona_id                     number
                                   constraint d50_appuntament_persona_id_fk
                                   references d50_persona on delete cascade not null,
    data_inizio                    date not null,
    data_fine                      date not null,
    descrizione                    varchar2(100 char)
)
;

-- table index
create index d50_appuntamento_i1 on d50_appuntamento (persona_id);
create index d50_appuntamento_i2 on d50_appuntamento (tipo_appuntamento_id);

-- views
create or replace view d50_appuntamento_vw as
select a.id,
       a.data_inizio,
       a.data_fine,
       a.descrizione,
       ta.descrizione as tipo_appuntamento,
       ta.classe_colore,
       p.nome persona,
       p.email email_persona 
  from d50_appuntamento a
  join d50_tipo_appuntamento ta on a.tipo_appuntamento_id = ta.id
  join d50_persona p on a.persona_id = p.id;
 
-- insert tipo_appuntamento
insert into d50_tipo_appuntamento (codice,descrizione,classe_colore)  values('PRIMO_APPUNTAMENTO','Primo Appuntamento','apex-cal-blue');
insert into d50_tipo_appuntamento (codice,descrizione,classe_colore)  values('ALTRO_APPUNTAMENTO','Altro Appuntamento','apex-cal-yellow');
insert into d50_tipo_appuntamento (codice,descrizione,classe_colore)  values('ULTIMO_APPUNTAMENTO','Ultimo Appuntamento','apex-cal-green');

-- insert cliente
insert into d50_persona (nome,email) values('Rossi Macaria','macaria.rossi@email.it');
insert into d50_persona (nome,email) values('Ferrari Mafalda','mafalda.ferrari@email.it');
insert into d50_persona (nome,email) values('Russo Maida','maida.russo@email.it');
insert into d50_persona (nome,email) values('Bianchi Mara','mara.bianchi@email.it');
insert into d50_persona (nome,email) values('Romano Marcella','marcella.romano@email.it');
insert into d50_persona (nome,email) values('Gallo Margherita','margherita.gallo@email.it');
insert into d50_persona (nome,email) values('Costa Marianna','marianna.costa@email.it');
insert into d50_persona (nome,email) values('Fontana Mariella','mariella.fontana@email.it');
insert into d50_persona (nome,email) values('Conti Marina','marina.conti@email.it');
insert into d50_persona (nome,email) values('Esposito Marinetta','marinetta.esposito@email.it');
insert into d50_persona (nome,email) values('Ricci Marita','marita.ricci@email.it');
insert into d50_persona (nome,email) values('Bruno Martina','martina.bruno@email.it');
insert into d50_persona (nome,email) values('Galli Menardo','menardo.galli@email.it');
insert into d50_persona (nome,email) values('Moretti Meneo','meneo.moretti@email.it');
insert into d50_persona (nome,email) values('Marino Mercurio','mercurio.marino@email.it');
insert into d50_persona (nome,email) values('Greco Metrofane','metrofane.greco@email.it');
insert into d50_persona (nome,email) values('Barbieri Michele','michele.barbieri@email.it');
insert into d50_persona (nome,email) values('Lombardi Minervino','minervino.lombardi@email.it');
insert into d50_persona (nome,email) values('Giordano Mario','mario.giordano@email.it');
insert into d50_persona (nome,email) values('Cassano Martino','martino.cassano@email.it');
insert into d50_persona (nome,email) values('Colombo Massimiliano','massimiliano.colombo@email.it');
insert into d50_persona (nome,email) values('Mancini Matroniano','matroniano.mancini@email.it');
insert into d50_persona (nome,email) values('Longo Mattia','mattia.longo@email.it');
insert into d50_persona (nome,email) values('Leone Maurizio','maurizio.leone@email.it');
insert into d50_persona (nome,email) values('Martinelli Medardo','medardo.martinelli@email.it');

/*
persona
  nome vc50 /nn /unique
  email vc60 /nn

tipo_appuntamento
  codice vc50 /nn /unique
  descrizione vc100 /nn
  classe_colore vc50 

appuntamento
  data_inizio d /nn
  data_fine d /nn
  tipo_appuntamento_id /nn
  persona_id /nn
  descrizione vc100 

# settings = { prefix: "D50", PK: "IDENTITY", semantics: "CHAR", DB: "12C", drop: true, language: "EN", APEX: true }
*/
/*
apex-cal-red
apex-cal-cyan
apex-cal-blue
apex-cal-bluesky
apex-cal-darkblue
apex-cal-green
apex-cal-yellow
apex-cal-silver
apex-cal-brown
apex-cal-lime
apex-cal-white
apex-cal-gray
apex-cal-black
apex-cal-orange
*/

/*
    update d50_appuntamento
       set data_inizio = to_date(:APEX$NEW_START_DATE, 'YYYYMMDDHH24MISS'),
           data_fine   = to_date(:APEX$NEW_END_DATE  , 'YYYYMMDDHH24MISS')
     where id = :APEX$PK_VALUE;
*/